
pipeline {
    agent any
    

    stages {
        stage ('Terraform Init'){
            steps {
	    	sh "ls -all"
	    	sh "cd tf_files && ls -all"
                sh "terraform init"
            }
        }
        stage ('Terraform Plan'){
            steps {
	    	sh "cd tf_files && ls -all"
                sh "terraform plan" 
            }
        }
        stage ('Terraform Apply'){
            steps {
	    	sh "cd tf_files"
                sh "terraform apply --auto-approve"
            }
        }

        stage('TF Destroy Confirm?') {
            steps {
                script {
                    timeout(time: 4, unit: 'MINUTES') {
                        input(id: "TF Destroy", message: "DO you want to destroy created Resources?", ok: 'Destroy')
                    }
                }
            }
        }
        stage ('Terraform Destroy'){
            steps {
	    	sh "cd tf_files"
                sh "terraform destroy --auto-approve"
            }
        }
    }
}
